[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
swings_dot_fun = "8DNN53jopWc89XcSs5FEm8YncwDmUjMUmnzLg3dUBKA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sahil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/createTokenAndBondingCurve.test.ts" # Current test suite in progress, run directly with `anchor test` for convenience
# Test suites that can be run by executing `anchor localnet` in another terminal, and 
test_initialization = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialization.test.ts"
test_set_platform_config = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/setPlatformConfig.test.ts"


[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./dumped-programs/token_metadata_program.so"